### PR TITLE
feat:wow ~ add wow refresh button

### LINKED ISSUE #6: Add refresh button to rendered JSON response
Instead of having to refresh the entire page, it would be nice to be able to simply refresh the example output.

### PR DESCRIPTION
**Pull request by schalkneethling**
Adds a button to easily load a new Wow!

fix #6

### CODE REVIEW

**Comment by amamenko** [comment]
Hi,

Button itself looks good, I like it. A couple of quick changes I'd like to see for the commit, though:

1. Remove the extra empty lines around the button wrapper in App.js (lines 173 and 179.)
2. Center the button and add a bit of margin below before the **Multiple Results** section, I would style the "refresh-button-wrapper" class with something like: `
    display: flex;
    justify-content: center;
    margin-bottom: 2rem;
`

Thanks!

**Comment by schalkneethling** [comment]
@amamenko Thank you for the feedback. I have updated the pull request with the suggested changes.

**Review by amamenko — CHANGES_REQUESTED** [review]
Thanks for removing the extra line breaks, JSX for button looks good.

What I was talking about when I mentioned centering the button was not centering the button _contents_ but rather the _button wrapper_ itself so the entire button is situated in the center.

Again, something like
```
.refresh-button-wrapper {
  display: flex; 
  justify-content: center; 
  margin-bottom: 2rem;
}
```
should suffice. You can set the margin-bottom CSS on either the wrapper or leave it as-is on the "wow-button" class.

**Comment by schalkneethling** [comment]
@amamenko Whoops, my bad. 😄

**Comment by schalkneethling** [comment]
@amamenko updated.

**Review by amamenko — APPROVED** [review]
Thanks for making those changes!
Looks good to me, I'll merge your refresh button in 👍

**Pull request merged**
